version: 0.1
phases:
  install:
    commands:
      - npm install -g serverless@1.27.3
      - npm install
  build:
    commands:
      - serverless deploy
  post_build:
    commands:
      - touch dummy.zip
artifacts:
  files:
    - dummy.zip
